### ISSUE TITLE
Encountered an ConnectionError exception while doing DPM operations

### ISSUE THREAD

**Issue by penny56** [zhmcclient/python-zhmcclient#1036]
**Describe the bug**
When I did some DPM operations like create partitions, attach sgs, sometimes it might encounter an ConnectionError exception, the exception response the msg:
**_ConnectionError(message="('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))")_**

This only happened when the Hmc is 2.16.0 and system is zThemis GA1.5, when I changed the environment to Hmc 2.15.0 on the zThemis GA1.5, the operation behaves good.

Anything you need to investigate, please feel free to let me know.

**To Reproduce**
This exception occurred during some operations, like create partitions, create vNics, attach sgs, but not always go exception.

**Expected behavior**
No ConnectionError Exception

**Environment information**
% python3 -m zhmcclient.debuginfo
Operating system: Darwin 21.5.0 on arm64
Python implementation: CPython 3.8.9 (64 bit, wide unicode)
Python version: 3.8.9
zhmcclient version: 1.3.0
* HMC version: 2.16.0
* HMC API version: SC27-2638-04b

**Comment by andy-maier** [comment]
I also encountered that on our z16 test systems.
We already started talking about this with the HMC team, but there is no solution at this point.
I think it would be good if you reported this as a problem using the HMC "report a problem" mechanism, so they can get the associated log files.

**Comment by penny56** [comment]
Thanks Andy for the investigating. Today I did some test to do some DPM operations by hmc api without zhmcclient package, and no this connection issue occurred. So I think it's probably not a hmc api point, more likely a zhmcclient point.

Thanks.

**Comment by andy-maier** [comment]
Hi @penny56 . The Z team found that the fix in MCL P30805.005 also fixes this problem. That MCL is in D51C HMC bundle H05. Please have your HMC upgraded accordingly, and let me know whether that fixed the issue.
