### ISSUE TITLE
Unable to activate/deactivate LPARs on z16

### ISSUE THREAD

**Issue by Amanda-Satrio** [zhmcclient/python-zhmcclient#1039]
**The Issue**
Encountered an error when attempting to activate LPARs on Artemis: 
```
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'
```

**To Reproduce**
The first step is to set the IP address, username, password, CPC, and LPAR variables. 
After the variables are set, I called the lpar.activate() function with the parameters: 
wait_for_completion=True, allow_status_exceptions=True, force=True

This is the exact script that I recreate to use the activate() function from zhmcclient (assuming the variables are already set): 
```

def activate_python(hmc_ip, hmc_user, hmc_passw, cpc, lpar):
    session = zhmcclient.Session(hmc_ip, hmc_user, hmc_passw, verify_cert=False,
                                 retry_timeout_config=zhmcclient.RetryTimeoutConfig(connect_timeout=3600))
    client = zhmcclient.Client(session)
    cpc = client.cpcs.find_by_name(cpc)
    lpar_object = cpc.lpars.find_by_name(lpar)
    lpar_object.activate(wait_for_completion=True, allow_status_exceptions=True, force=True)


activate_python(hmc_ip, hmc_user, hmc_passw, cpc, lpar)
```

**Expected behavior**
The expected behavior is when running the function lpar.activate(), the LPAR should be activated

I was able to activate LPARs on a Themis machine using lpar.activate().

However, with Artemis this error appears: 
```
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'
```
Additional note: 
I was able to manually recreate the activation process using only RESTAPIs in a python script (non zhmc), and that resulted in a successful activation of the same LPAR/system combo that was used above with zhmc.  

**Environment information**
* Output of `python -m zhmcclient.debuginfo`:
```
Operating system: Linux 5.10.47-linuxkit on x86_64
Python implementation: CPython 3.6.9 (64 bit, wide unicode)
Python version: 3.6.9
zhmcclient version: 1.1.1
amandasatrio@Denisas-MacBook-Pro:/ssc_devel/zrobot/zRobot_SSCVERIF/tests$ python3 -m zhmcclient.debuginfo
Operating system: Linux 5.10.47-linuxkit on x86_64
Python implementation: CPython 3.6.9 (64 bit, wide unicode)
Python version: 3.6.9
zhmcclient version: 1.1.1
```
* HMC version: 2.16.0
* HMC API version: Not sure how to get this version number

**Comment by andy-maier** [comment]
Seems to be the same issue as reported in https://github.com/zhmcclient/python-zhmcclient/issues/1036

**Comment by andy-maier** [comment]
Hi @Amanda-Satrio . The Z team found that the fix in MCL P30805.005 also fixes this problem. That MCL is in D51C HMC bundle H05. Please have your HMC upgraded accordingly, and let me know whether that fixed the issue.
