### ISSUE TITLE
'Connection aborted.' issue in 1.4.0

### ISSUE THREAD

**Issue by penny56** [zhmcclient/python-zhmcclient#1049]
**Describe the bug**
Hi Andy, I think it's probably the same issue as #1036, I upgraded the zhmcclient package to 1.4.0 and the driver using Bundle H07+S08/S08a, here is the response message:
_HTTPSConnectionPool(host='9.12.35.135', port=6794): Max retries exceeded with url: /api/storage-groups?cpc-uri=%2Fapi%2Fcpcs%2Ffe3cc6fe-d322-3231-818f-0f6c2bb0863f (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))), reason: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))_

**To Reproduce**
Not specific operation, some operations may encounter this issue, like add new vNic in partition, attach fcp storage groups, etc...

**Expected behavior**
No disconnect occurred.

**Environment information**
* Output of `python -m zhmcclient.debuginfo`:
* HMC version:
* HMC API version:

Same with issue #1036, only occurred in hmc 2.16.0, operations in zThemis is good.

_# python3 -c "import zhmcclient; print(zhmcclient.debuginfo())"
os_name: Linux
os_version: 3.10.0-1160.62.1.el7.x86_64
cpu_arch: x86_64
bit_size: 64
unicode_size: wide
python_impl: CPython
python_impl_version: 3.6.8
python_version: 3.6.8
zhmcclient_version: 1.4.0_

**Comment by penny56** [comment]
Double checked the MCL P30805.005 also included in the test hmc.
![image](https://user-images.githubusercontent.com/13374916/187582290-b807ee3a-f316-4b82-97bf-e839d12d8d5d.png)

**Comment by penny56** [comment]
Hi Andy, any comments?
I did more test, the 'Connection aborted' error not always occurred. I made a loop to list storage groups in a cpc, the 'Connection aborted' occurred mostly between the fifth to tenth times.

`Error: Cannot list storage groups of CPC A90: ConnectionError: HTTPSConnectionPool(host='9.12.35.135', port=6794): Max retries exceeded with url: /api/storage-groups?cpc-uri=%2Fapi%2Fcpcs%2Ffe3cc6fe-d322-3231-818f-0f6c2bb0863f (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))), reason: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by andy-maier** [comment]
Hi @penny56 Sorry for the delay. Then this means that the MCL P30805.005 that was recommended by the Z team does not solve the problem in all cases.

Are you from IBM?
If yes, can you ping me on Slack?
If no, can you please open a PMR to report this?

**Comment by penny56** [comment]
Hi Andy, it's no problem, contact you on Slack.

**Comment by penny56** [comment]
This issue not appeared anymore in current system, close this ticket.
