### ISSUE TITLE
Example programs in examples folder should have more descriptive file names

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#133]
### Actual behavior
At the moment the names of files in the example folder are example0, example1, ...
We should provide more descriptive names so that an example can be picked without
having to look into the file to find an appropriate example.

### Execution environment

* zhmcclient version:
* Operating system (type+version):

**Comment by abrezovsky** [comment]
**Here are some of my ideas:**

example0.py > apiVersion.py
example1.py > listCPCandLPAR.py
example2.py > lparOperations.py
example3.py > getProperties.py
example4.py > asyncInterface.py
example5.py > CRUD.py
example6.py > activationProfiles.py
example7.py > JMSnotify.py
example8.py > additionalResources.py

Maybe have example_ prepend the file names like that yaml file?

**Comment by andy-maier** [comment]
PR #155 fixes this.
