### ISSUE TITLE
Documention of for cpc install_and_activate is wrong for ec_levels parameter

### ISSUE THREAD

**Issue by schaufle** [zhmcclient/python-zhmcclient#1373]
The documentation for cpc install_and_activate() in the _cpc.py source file states

```
            ec_levels (list of tuple(ec,mcl)): Updates to be installed on the
            SE of this CPC, as a list of tuples (ec, mcl) where:

              - ec (string): EC number of the EC stream (e.g. "P30719")
              - mcl (string): MCL number within the EC stream (e.g. "001")
```

When I called it with
`[("P30716", "26")]`
I got an error. After reading the WSAPI documentation I tried
`[{"number": "P30716", "mcl": "26"}]`
This worked as expected.

**Comment by andy-maier** [comment]
@schaufle Ralf, the question is how we want the interface of the zhmcclient method to be for the ec_levels parameter:
* list of tuple (the method converts it to list of dict)
* list of dict (passed directly)

I tend to use list of dict.
What is your view?

**Comment by schaufle** [comment]
I didn't think of that aspect.
I find the list of tuples more convenient.
On the other hand a list of dicts would better match the official WSAPI
documentation. That ist probably a more important point.

Andreas Maier ***@***.***> schrieb am Mo., 25. Dez. 2023,
09:52:

**Comment by andy-maier** [comment]
Let's go with the list of dict. After all, this is a programming interface. When we add support in the zhmccli, we still can do things like comma-separated list of "EC.MCL" strings.

**Comment by andy-maier** [comment]
@schaufle Ralf,
I have created PR #1380 that chanhes the implementatopn to support list(tuple(ec,mcl)).
Please let me know whether you agree.
This also means you need to change your code to provide the ec_levels parameter as list(tuple(ec,mcl)).
