### ISSUE TITLE
Support LPAR OS message interactions

### ISSUE THREAD

**Issue by abrezovsky** [zhmcclient/python-zhmcclient#148]
### Actual behavior

Interaction with LPAR OS messages is not currently supported.

### Expected behavior

Use Open OS Message Channel and/or Send OS Command operations to support interaction with LPAR OS messages.

HMC API Pages 513-517

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): Ubuntu 16.10 (applies to any)

**Comment by abrezovsky** [comment]
This would need some support for the Java Message Service. Would we need to find a package for JMS?

**Comment by leopoldjuergen** [comment]
I think we have to implement the LPAR operation 'Open OS Message Channel' and combine it with example7.py. To connect to the API message broker we use STOMP in the example5.

**Comment by abrezovsky** [comment]
Ah, OK, I didn't realize there was some flavor of that support in there already, I'll try to understand what's there already and then maybe start a new branch.

**Comment by abrezovsky** [comment]
After looking at the jms_notifications example and how STOMP works, is the best solution  to just pass along the JMS topic to the client and allow them to set up STOMP themselves as in that example? A method in the Lpar class. I think that would be a good minimum.

Past that, we could implement certain aspects of the STOMP process within our wrapper and leave certain parts to the user?

I'm not exactly sure what that would be and/or how it would fit into our goal of providing a "thin wrapper".

**Comment by andy-maier** [comment]
I have a suggestion on the design of the external API for this support:
1. The operation for opening the message channel should be a method on the `Partition` and `Lpar` classes, respectively, that returns an object of a new `MessageChannel` class.
2. The `MessageChannel` class has a method `get_next()` that waits for the next message on the JMS notification topic for the channel, and returns it to its caller once the next message has been received.

This way, the whole area of multithreading/multiprocessing/eventing/notification can be done in any way by the user, and the zhmcclient package does not need to select a particular multiprocessing or eventing model.

Comments, please.

**Comment by abrezovsky** [comment]
I think what you are proposing would require the method to kick off a listener (see the example) in a new thread (or process). 

For now I'm going to implement an `open_os_message_channel()` method for `Partition` and `Lpar` to expose the HMC API at the very least.

**Comment by andy-maier** [comment]
No, the open method would not have to start a thread.

**Comment by abrezovsky** [comment]
I added in basic support through an open_os_message_channel method to the two classes. The pull request is open. I suppose we can keep this issue open if we feel we need to add more support?

**Comment by andy-maier** [comment]
PR #167 and #168 add support for the 'Open OS Message Channel' operation.

What is still open, is support for the 'Send OS Command' operation.

**Comment by leopoldjuergen** [comment]
I think we can close this issue. The missing topics are tracked by following issues:

#171 Add Support for Send OS Command' operation
#170 Add zhmcli command for JMS notification receiver
#169 Add Unit Tests for JMS notification receiver

**Comment by andy-maier** [comment]
Ok. I am closing this issue here.
