### ISSUE TITLE
Name 'partition' is not defined in example5.py

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#149]
### Actual behavior
When running example5.py and partition does not already exist, we get this error message:
```
...
Finding Partition by name=TestPart1 on CPC P000AABB ...
Traceback (most recent call last):
  File "./example5.py", line 105, in <module>
    print("Partition %s does not exist yet" % partition.name)
NameError: name 'partition' is not defined
```

### Expected behavior
No error message.

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): Ubuntu 14.04

**Comment by andy-maier** [comment]
Fixed in PR #150
