### ISSUE TITLE
Add optional 'name' parameter to filter manager.list() method returns

### ISSUE THREAD

**Issue by abrezovsky** [zhmcclient/python-zhmcclient#157]
### Actual behavior

Calls to manager.list() will return all objects.

### Expected behavior

User able specify a 'name' argument to limit returned objects.

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): Applies to any

**Comment by abrezovsky** [comment]
The HMC API supports an optional name parameter to limit returned objects on a list operation.

Through some testing I determined that the fastest way to get the status of an object is to get the list from the manager, iterate through the objects, and look at the 'status' element of the properties dictionary. The list API call to list is roughly 150x faster than pulling the full properties. 

Allowing a name filter on the list would make the process of getting the status through this method cleaner.

**Comment by andy-maier** [comment]
The `find()` and `findall()` methods support filtering.

**Comment by andy-maier** [comment]
Also, PR #136 adds filtering to `list()` (a by-product ofthat PR, not its original intention).

**Comment by abrezovsky** [comment]
Oops, didn't realize. Guess I got a little ahead of myself.

I mainly wanted it in list() because of the performance boost.

I'll see what if I can do what I'm trying to do with your solution, no purpose in duplicating effort.
