### ISSUE TITLE
Add zhmc CLI command for JMS notification receiver

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#170]
The command should return the pending JMS messages and return immediately . If the option -f (--follow) is added JMS messages should be added until the user terminates it with CTRL-C.

**Comment by andy-maier** [comment]
At this level of generality, the command will need the notification token as input. That means, before this makes sense, we need CLI commands that return these tokens. We don't deal with asynchronous job completion in the CLI,so the only remaining possible notifications are:
- object (property/status) changes
- audit
- security
- os message channel

It seems to me that these areas should be handled separately in the CLI. That allows hiding the notification topics.

For OS messages, how about:
* `zhmc partition show-os-messages <cpc-name> <partition-name> [-f]`
* `zhmc lpar show-os-messages <cpc-name> <lpar-name> [-f]`

For object / security / audit notifications, we need to get some more understanding on how that works.

**Comment by andy-maier** [comment]
We need to discuss where we want to go with this idea.

**Comment by leopoldjuergen** [comment]
I like the proposal for show-os-messages:
zhmc partition show-os-messages <cpc-name> <partition-name> [-f]
zhmc lpar show-os-messages <cpc-name> <lpar-name> [-f]

**Comment by andy-maier** [comment]
For OS messages, this has been addressed by PR #294.

**Comment by andy-maier** [comment]
This issue has been copied to zhmcclient/zhmccli#7
