### ISSUE TITLE
Add Support for Send OS Command' operation

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#171]

**Comment by abrezovsky** [comment]
This API call returns a JSON object with no content. Is this something we should return?

**Comment by andy-maier** [comment]
I don't think so. Look at the recent redesign of the return value of async methods in PR #182 - we try to return entities that make sense, not strictly the response body. So returning None is the right thing to do in this casew, IMO.

Having said that: One of the big downsides of this HMC operation is that it does not return the return code or the stdout/stderr of the command that was executed. Apparently, the command output can be retrieved via the OS message channel, and someone suggested that the ability to set the prompt could be used to correlate the messages in the OS message channel with the command that was sent. So we should be able to build a synchronous method that takes a command string and that returns its output. Don't think we can get the return value that way, though.

**Comment by abrezovsky** [comment]
Alright, thanks for the input. I see what you're saying about the command output, that's something we can probably try to tackle a bit later.

**Comment by abrezovsky** [comment]
Implemented in branch `send-os-command,` needs testing

**Comment by andy-maier** [comment]
Addressed in PR #194.
