### ISSUE TITLE
Doc says that partition.start() and partition.stop() should return None, but it retuns something

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#178]
### Actual behavior
partiton.start() returns a Dict like this:

OrderedDict([(u'status', u'complete'), (u'job-status-code', 200), (u'job-results', OrderedDict()), (u'job-reason-code', 0)])

### Expected behavior
Along the docs [1], I would ave expected that it returns None

"Returns:	If wait_for_completion is True, returns None."
And the docs also says:
"start(wait_for_completion=True)" is the default

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): ubuntu 14 x86

[1] http://python-zhmcclient.readthedocs.io/en/stable/resources.html#partitions

**Comment by scheuran** [comment]
This has impact on the nova-dpm project, as it is currently using this returned object. More details see https://bugs.launchpad.net/nova-dpm/+bug/1660905

**Comment by andy-maier** [comment]
Fixed with PR #182.
However, note that there is an incompatible change.
