### ISSUE TITLE
zhmc CLI: bad line breaks when partition has more than one nic

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#179]
### Actual behavior
Show the partition details of an Partition that has at least 2 NICs attached:
> zhmc partition show <CPC> <Partition>

The zhmccli does not do any line breaks. This gets very ugly when the *uri fields (list of URIs).
As there's no line break, the terminal breaks the line - which does not look nice at all!

### Expected behavior
Ideally the zhmccli would make a line break after each uri list item.

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): ubuntu14 (x86)

**Comment by andy-maier** [comment]
This issue has been copied to zhmcclient/zhmccli#9
