### ISSUE TITLE
zhmccli:  result table not drawn properly

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#180]
### Actual behavior
```
$ zhmc cpc list
/+----------+------------------+
| name     | status           |
|----------+------------------|
| P000S67B | service-required |
+----------+------------------+
```

-> Due to the spinner "/", the top line of the table starts and ends one character after the rest of the table

### Expected behavior

Table properly drawn
-> This is nothing that really hurts, it's just something I realized.

### Execution environment

* zhmcclient version:
* Operating system (type+version):

**Comment by andy-maier** [comment]
Probably the same issue as #116.
Leaving both open for now.

**Comment by andy-maier** [comment]
This is the same issue as #116, which has been addressed by a fix in the click-spinner package. Closing this one as a duplicate.
