### ISSUE TITLE
Deferred status transition with Lpar.activate() and deactivate()

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#191]
When the `Lpar.activate()` and `deactivate()` methods complete (e.g. by returning after being called with `wait_for_completion=True`), the LPAR state may not have reached the desired state, and a subsequent status retrieval still reports the old state.

This does not happen always, and the exact circumstances are not fully understood at this point.

As a result, users of the zhmcclient have to code around this and loop on status retrieval until the desired state is reached.

The zhmcclient could take care of that by performing the stats polling inside of these methods for the `wait_for_completion=True` case, making life easier for the user. In the `wait_for_completion=False` case, adressing this is more complex, but not impossible, given that we have PR #182: The async method could return a new subclass of `Job` that implements its check and wait methods such that completion includes polling for the desired status.

Discussion points:
* Should we do this at all?
* Should a timeout be added? (see Issue #6)

**Comment by abrezovsky** [comment]
I've encountered this issue as well. For activate I've been seeing a delay of between 2 and 5 seconds (I use sleep to work around this). I believe the same problem occurs with the load operation.

I think that we should only take care of the polling in the `wait_for_completion=True` case and that we definitely need a timeout. How long that timeout would be might take some investigation. From my experience, it should be no longer than 10 seconds.

**Comment by andy-maier** [comment]
Ok, good. Yes, I think we also saw it on load. I'll take that on, then.

**Comment by andy-maier** [comment]
Fixed in PR #195.

**Comment by andy-maier** [comment]
Closing this manually, as PR #195 was merged.

**Comment by abrezovsky** [comment]
Hit following exception while trying to activate an LPAR. The LPAR is successfully activated but this pops up after a few seconds:

`lpar.activate(True)
  File "<decorator-gen-11>", line 2, in activate
  File "C:\Python35\lib\site-packages\zhmcclient\_logging.py", line 132, in wrapper
    result = func(*args, **kwargs)
  File "C:\Python35\lib\site-packages\zhmcclient\_lpar.py", line 250, in activate
    self._wait_for_status("non-operating", status_timeout)
  File "C:\Python35\lib\site-packages\zhmcclient\_lpar.py", line 525, in _wait_for_status
    assert len(lpars) == 0
AssertionError`

**Comment by andy-maier** [comment]
Andrew, you are right with both (assert and status value). Obviously, this was not tested (shame on me...). I'll fix that and test it.

**Comment by andy-maier** [comment]
Also, I'll do one more thing Juergen brought up: When waiting for the desired status, we should also check status "exceptions" so the waiting ends in case of errors.

Finally, I'll rebase it on PR #206 and use the new RetryTimeoutConfig object to have the async completion and lpar status transition timeouts specified there.
