### ISSUE TITLE
Executing zhmc -help opens interactive session

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#196]
### Actual behavior
Executing `zhmc -help` opens interactive session

### Expected behavior
An error message that `-help` is not a supported option

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version):

**Comment by andy-maier** [comment]
Initial analysis:
* The erroneous behaviour described in this issue exists for all invalid options that are specified with a single leading hyphen, e.g. `zhmc -foo`
* Invalid options that are specified with two leading hyphens are correctly rejected, e.g. `zhmc --foo`.
* `zhmc --help` (with two leading hyphens) correctly shows the help without entering interactive mode.

**Comment by andy-maier** [comment]
Mitigated by PR #198, which improves the help text.

**Discussion point:** Do we think this is good enough?

**Comment by andy-maier** [comment]
Will close this one by end of next week if nobody objects.

**Comment by andy-maier** [comment]
Closing this issue as nobody objected.
