### ISSUE TITLE
Description of how to quit interactive console not in help text

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#197]
### Actual behavior
I was trying to figure out how to exit the interactive console

quit()
quit
exit
exit()
is all not working

Finally :q did it.  Does it make sense to have that somehwere in the zhmc clients help?
In the docs it is used in one of the examples

### Execution environment

* zhmcclient version:
* Operating system (type+version):

**Comment by andy-maier** [comment]
Fixed in PR #198.
