### ISSUE TITLE
Logging feature request

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#205]
### Actual behavior
With debug logs enabled, the log is getting flooded.

DEBUG zhmcclient._session [-] Entering Session.get() from (pid=11618) wrapper /usr/local/lib/python2.7/dist-packages/zhmcclient/_logging.py:131
DEBUG zhmcclient._session [-] Entering Session.logon() from (pid=11618) wrapper /usr/local/lib/python2.7/dist-packages/zhmcclient/_logging.py:131
DEBUG zhmcclient._session [-] Entering Session.is_logon() from (pid=11618) wrapper /usr/local/lib/python2.7/dist-packages/zhmcclient/_logging.py:131
DEBUG zhmcclient._session [-] Leaving Session.is_logon() from (pid=11618) wrapper /usr/local/lib/python2.7/dist-packages/zhmcclient/_logging.py:133
DEBUG zhmcclient._session [-] Leaving Session.logon() from (pid=11618) wrapper /usr/local/lib/python2.7/dist-packages/zhmcclient/_logging.py:133

### Expected behavior

I'm thinking of a log level that provides the following
- All requests made to the HMC including request bodies (the json for the request)
- All responses (http status code) from the HMC including response bodies (the json result)

Maybe it makes sense to prevent some logging form the session object (password)

I'm not interested in the Session.logon messages that flood the log at the moment. Also the debug logs just contain the URL that was called, but not the bodies.

### Execution environment

* zhmcclient version:
* Operating system (type+version):

**Comment by andy-maier** [comment]
Addresses with PR #209.
