### ISSUE TITLE
Verify multi-threading support

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#210]
The zhmcclient so far was not designed with multi-threading capability in mind. It is not clear whether there are any issues. The OpenStack Nova DPM driver uses the same Session object in multiple threads.

**Comment by abrezovsky** [comment]
I have attempted multi-threading with my external scripts (utilizing zhmcclient) and found that the Python GIL spoils most of the potential gains. This should be considered as well.

**Comment by andy-maier** [comment]
**Discussion Points:**
* Is the list of potential issues complete?
* Is the mitigation acceptable to use separate `Session`, `Client` and `NotificationReceiver` objects for each concurrent thread?

**Comment by andy-maier** [comment]
PR #244 adds content to the Concepts chapter and it has a section "multi-threading considerations" in which we state that each session, client and notification receiver object can be used by only one thread at a time.
I consider this the solution to this issue.
