### ISSUE TITLE
zhmccli does not implement the well known options -f and -y. instead --yes is used

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#213]
### Actual behavior
Enforcing a deletion can be done with --yes

### Expected behavior
Typically -f or -y are the options that used widely. 

### Execution environment

* zhmcclient version:
* Operating system (type+version):

**Comment by andy-maier** [comment]
**Discussion point:** Which options do we want to support for skipping the confirmation prompt.

**Comment by leopoldjuergen** [comment]
I would propose '-y'.

**Comment by andy-maier** [comment]
I agree, let's add `-y` to the existing `--yes` options.

**Comment by andy-maier** [comment]
Addressed by PR #221, which adds a `-y` option to every `--yes` option.
