### ISSUE TITLE
Pass password to zhmc on the command line

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#225]
Add a switch –p to pass the password on the command line.

Example:
zhmc -o plain -h ${HMC} -u ${HMCUSER} -p ${HMCPASSWD} lpar list ${CECDCP}

The -p option should be considered the least secure of all password options.

**Comment by andy-maier** [comment]
Agreed.

**Comment by andy-maier** [comment]
Fixed in PR #227.
