### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by sreeteja7** [zhmcclient/python-zhmcclient#233]
### Actual behavior
Typo in this line :
Derived from zhmcclient_mock.FakedBaseResource, see there for common metrhods and attributes.
### Expected behavior

Derived from zhmcclient_mock.FakedBaseResource, see there for common methods and attributes.
### Execution environment

* zhmcclient version:zhmcclient 0.11.1.dev22 documentation
* Operating system (type+version):Windows

**Comment by andy-maier** [comment]
Fixed in PR #235.
