### ISSUE TITLE
zhmccli: reference the adapters by adapter-id in the update command

### ISSUE THREAD

**Issue by kellymaud** [zhmcclient/python-zhmcclient#237]
for example  
name: "CCA 0100"
 adapter-id: 100

### Actual behavior
`$ zhmc adapter update CPC "CCA 0100" --name "EP11_00" `

### Expected behavior
`$ zhmc adapter update CPC 100 --name "EP11_00" ` 

### Execution environment

* zhmcclient version: 0.10.0
* Operating system (type+version): Ubuntu 16.04.2 LTS

**Comment by andy-maier** [comment]
Kelly, we cannot just accept an ID value. What if the ID of one resource is the name of another one? We also do not want to change to using IDs and drop support for the use of names. Names are guaranteed to be unique for HMC resources.

We could add an option that allows specifying whether the provided string is an ID or a name. Please let us know whether this is acceptable to you folks.

Do you intend to use auto-assigned IDs?

**Comment by kellymaud** [comment]
Andreas, 
Nevermind then, I already have a workaround in my code so it is not a problem.
