### ISSUE TITLE
Add support for HMC task "Load from Removable Media"

### ISSUE THREAD

**Issue by fheimes** [zhmcclient/python-zhmcclient#280]
### Actual behavior
"Load" is supported, but not "Load from Removable Media"

### Expected behavior
becoming able to start an installation
(with the help of FAI tools like preseed, autoyast or kickstart
a complete non-interactive installation can be done)

### Execution environment
for non-DPM systems
requires that the HMC exposes the "Load from Removable Media" task via it's web API

* zhmcclient version:
* Operating system (type+version):
* HMC version:
* CPC version:

**Comment by xnox** [comment]
+1 from Ubuntu.

**Comment by andy-maier** [comment]
It is still not supported by the HMC. Sorry for that. Closing the issue.

**Comment by xnox** [comment]
I guess it's worth mentioning that the future means PXE boot with DPM. As long as that can be triggered via the API (i believe it is).
