### ISSUE TITLE
CLI: initial-cp-processing-weight shouldn't change when not set them during zhmc partition update

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#405]
### Actual behavior
We lose the setting of initial-cp-processing-weight and initial-ifl-processing-weight property
because it is set on 'zhmc partition create' and disappears on the next 'zhmc partition update'.

### Expected behavior
initial-cp-processing-weight and initial-ifl-processing-weight stay with the same value if not set during the 'zhmc partition update'.

### Execution environment

* zhmcclient version: 0.15.0
* Operating system (type+version):
* HMC version:
* CPC version:

**Comment by andy-maier** [comment]
Fixed in PR #406.
