### ISSUE TITLE
docs/development.rst issue in release instructions

### ISSUE THREAD

**Issue by KSchopmeyer** [zhmcclient/python-zhmcclient#410]
### Actual behavior
on line 251

        git branch --set-upstream-to origin/release-$MNU release-$MNU

Results in a usage message that includes a statement about using git push -u.  I think that
somewhere the structure/use of this command has apparently been modified.

### Expected behavior

I ignored the above command and used push -u on the first push for another project and that seemed to work.

### Execution environment

* zhmcclient version:
* Operating system (type+version):
* HMC version:
* CPC version:

**Comment by KSchopmeyer** [comment]
Forget it.  My error

**Comment by andy-maier** [comment]
Fixed in PR #415.
