### ISSUE TITLE
CLI: No way to set properties to null

### ISSUE THREAD

**Issue by simon-spinner** [zhmcclient/python-zhmcclient#426]
### Actual behavior
There is no way to set properties of a resource to null (at least that I am aware of):
nic update --vlan-id '' SSPSE test-ssc nic
--> Error: Invalid value for "--vlan-id":  is not a valid integer
nic update --vlan-id SSPSE test-ssc nic1
--> Error: Invalid value for "--vlan-id": SSPSE is not a valid integer
nic update --vlan-id null SSPSE test-ssc nic1
--> Error: Invalid value for "--vlan-id": null is not a valid integer
### Expected behavior
Certain fields in the DPM API allow for null values (e.g., the field vlan-id of a SSC management nic). If this field contains a value, it can be cleared by explicitly sending a JSON null value (see SPEC at http://www.json.org/) in an update request. There should be a way to specify null values in zhmc for such fields.

### Execution environment

* zhmcclient version: 0.16.0
* Operating system (type+version): Ubuntu LTS 16.04
* HMC version:
* CPC version:

**Comment by andy-maier** [comment]
I see two options on how to do that at the zhmc CLI:

Option 1:
* An option `--XXX` for a property that can be set to null gets a corresponding `-no-XXX` option. That would probably be the minority of options.
* An `--XXX` option and its corresponding `-no-XXX` option are mutually exclusive.

Option 2:
* An option `--XXX` for a property that can be set to null accepts a special string value 'null'. If there are string typed properties that can be set to null, and the string "null" is valid as a normal value, then we can add an option `--null-value YYYY` that sets the value one has to specify for an option to set the property to null, to `YYYY`.

**Comment by andy-maier** [comment]
This issue has been copied to zhmcclient/zhmccli#2
