### ISSUE TITLE
zhmcclient_mock/_urihandler.py:315: TypeError

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#441]
[test_27.log.txt](https://github.com/zhmcclient/python-zhmcclient/files/1309064/test_27.log.txt)

### Actual behavior
MetricsContextHandlersTests.test_create_get_delete_context fails due to a TypeError in file zhmcclient_mock/_urihandler.py, line 315.

This unit test error avoids to run successfully in Travis for master branch.

### Execution environment

* zhmcclient version: master

**Comment by andy-maier** [comment]
Circumvented in PR #442, and permanently fixed in PR #443.
