### ISSUE TITLE
Implement the 'set auto-start list' operation for DPM mode

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#472]
The Set Auto-Start List operation identifies a CPC's partitions
that are automatically started when the CPC is started.

* zhmcclient version: 0.18.0
* Operating system (type+version):
* HMC version: 2.13.1
* CPC version:

**Comment by andy-maier** [comment]
Needed for https://github.com/zhmcclient/zhmccli/issues/33
