### ISSUE TITLE
Can zhmc support ibm hmc rather than ibm z hmc？

### ISSUE THREAD

**Issue by lkx007** [zhmcclient/python-zhmcclient#494]
Can zhmc support ibm hmc rather than ibm z hmc？
I want to use “python-zhmcclient” for ibm hmc,but I got error.
And I found that in "/usr/lib/python2.7/site-packages/zhmcclient/_session.py", the _HMC_PORT is  6794,
but my hmc for ibm api port is 12443..
Any suggestions?

**Comment by andy-maier** [comment]
Hi. The zhmcclient supports only the HMC for Z systems (any generation of Z systems that supports the HMC Web Services API).

What kind of HMC do you intend to use? (Power systems, some storage system, something else)?

**Comment by andy-maier** [comment]
@lkx007 Any update on this one?

**Comment by lkx007** [comment]
@andy-maier  we download hmc from the following sites, and we are wondering if zhmc can support these hmc.

ftp://ftp.software.ibm.com/software/server/hmc/recovery_images

**Comment by andy-maier** [comment]
I apologize for the long delay; I missed your comment.
That is an HMC for the IBM Power systems. The zhmcclient supports only the HMC for IBM Z systems. I don't know of a Python client for the IBM Power HMC, but will ask.

**Comment by atthorst** [comment]
Hi @lkx007, I was pointed here from @andy-maier.  I am part of the Power Systems development team.

We have a REST API, for which clients can be built atop of, for the HMC.  You can see details [here](https://www.ibm.com/support/knowledgecenter/TI0003M/p8ehl/concepts/ApiOverview.htm).  To my knowledge, no one has taken that and built a python client on top of it.

If you are using NovaLink (which can be used in conjunction with an HMC), then you should look into the [pypowervm](https://github.com/powervm/pypowervm) project.  This is a python API that is used by many different users to control the virtualization on the system.  These projects include the PowerVM OpenStack drivers, IBM's PowerVC product, and even certain cloud providers.

I should also note that pypowervm does not support controlling an HMC.  Some people have tried it, but there are known issues with it and it is not an official support path.  The official support is for NovaLink based systems.

If you would like interactive help, the best place to find it would probably be the `#openstack-powervm` IRC channel.  Details [here](https://wiki.openstack.org/wiki/PowerVM).

Here are some details of NovaLink:

- [Overview and Architecture](https://www.ibm.com/support/knowledgecenter/en/POWER8/p8eig/p8eig_kickoff.htm)
 - [Wiki article](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Power%20Systems/page/Introducing%20PowerVM%20NovaLink)
 - YouTube showing [optional Platform Installer](https://www.youtube.com/watch?v=3veHtty-FTA&ab_channel=PowerVMChannel)
 - YouTube showing [installing NovaLink from an HMC](https://www.youtube.com/watch?v=LUcw5eDGCrI&ab_channel=PowerVMChannel)
 - [Using Software Defined I/O on PowerVM through PowerVC + NovaLink](https://www.ibm.com/support/knowledgecenter/en/SSXK2N_1.4.1/com.ibm.powervc.standard.help.doc/powervc_sdi.html)


Hope this helps!

**Comment by lkx007** [comment]
@andy-maier @atthorst  Thanks u a lot for your reply. It is very useful for me.
