### ISSUE TITLE
Could not list the storage groups

### ISSUE THREAD

**Issue by mayijieibm** [zhmcclient/python-zhmcclient#554]
### Actual behavior
I'm not sure I using the right way, so please correct me if I'm wrong. Thanks.

##########################
cpcs = client.cpcs.list()
for cpc in cpcs:
    print(cpc)
    if cpc.name == 'M257':
        storage_groups = cpc.storage_groups.list()
        for storage_group in storage_groups:
            print(storage_group)

##############################

Error code:
  _File "/Users/mayijie/eclipse-workspace/0705Python/Zhmcclient-py3/src/listcpc.py", line 25, in <module>
    storage_groups = cpc.storage_groups.list()
AttributeError: 'Cpc' object has no attribute 'storage_groups'

### Expected behavior
I expect the code could list the storage groups for M257 CPC, but it raise the exception.

### Execution environment

* zhmcclient version: 0.22.0
* Operating system (type+version): macOS 10.14.1
* HMC version: 2.14.0
* CPC version:

**Comment by mayijieibm** [comment]
Hi Andy,

I tried the cpc.list_associated_storage_groups() and it looks great, I saw the partition class also have the same method to list the storage groups attached to the partition. But when I run partition.list_associated_storage_groups(), it replied "AttributeError: 'Partition' object has no attribute 'list_associated_storage_groups'".

Could you take a look. Thanks.
https://python-zhmcclient.readthedocs.io/en/latest/resources.html?highlight=5#zhmcclient.Partition.list_attached_storage_groups

**Comment by andy-maier** [comment]
@mayijieibm The method on the Partition class is named list_*attached*_storage_groups(), while the method on the Cpc class is named list_*associated*_storage_groups(). The documentation of the method on the Partition class is consistent with its implementation.

I double checked the HMC WS API book on the terminology, and in "Storage Group object", it says: "A Storage Group object represents a single storage group associated with a DPM-enabled CPC. Storage groups define a set of FCP or FICON storage volume resources that can be attached to partitions". It has other places that also use these different terms for the relationships that way. These two relationships of the storage groups (to CPCs and to Partitions) are simply of different nature, and hence there are different terms for them.

**Comment by andy-maier** [comment]
The `list_storage_groups.py` example was fixed in PR #555.

Closing this issue. Please reopen it if there are problems with the fix, or open a new issue for new problems.

**Comment by mayijieibm** [comment]
Hi Andy,

Thanks for the detailed explanation, now I understand.
