### ISSUE TITLE
Question: Can we load a image from a ftp server in classic mode?

### ISSUE THREAD

**Issue by bjwswang** [zhmcclient/python-zhmcclient#591]
cpc is now in claasic mode. We need to load a image from ftp server

**Comment by bjwswang** [comment]
As far as I know, in classic mode, zhmcclient only support to load from `scsi` 
https://github.com/zhmcclient/python-zhmcclient/blob/master/zhmcclient/_lpar.py#L429
and from `dasd`
https://github.com/zhmcclient/python-zhmcclient/blob/master/zhmcclient/_lpar.py#L570
but now we need to load a linux image from ftp server repo, like http://ports.ubuntu.com/ubuntu-ports/dists/bionic/main/installer-s390x/current/images/generic/ 
do we support this ? if not, do we have a plan on this ?

**Comment by andy-maier** [comment]
Hi @bjwswang, I'll look into this now. Sorry for the delay.

**Comment by andy-maier** [comment]
Has finally been implemented in PR #1228 and released as version 1.10.0
