### ISSUE TITLE
lun-discovery-task - add support for "Start FCP Storage Discovery" operation

### ISSUE THREAD

**Issue by fredgnucc** [zhmcclient/python-zhmcclient#623]
### Execution environment

* zhmcclient version:
* Operating system (type+version):
* HMC version:
* CPC version:

HI Gentlemen , 

i am working on global automation project 

We have succesfully created some volume on a9000r in automated way .

But we need also to ingretated those lun into the hmc side on a storage-group : FCP mode 

For this we are still actually manually launching a lun discovery task in hmc via the storage group ui .

https://localhost/hmc/taskreq/687/1/storage-groups/33e286a0-53ce-11ea-b343-00106f2394a1/lun-discovery-task-for-cxn-report

![image](https://user-images.githubusercontent.com/38003140/76612503-bea20400-651c-11ea-9925-1d67066c03a7.png)

Do you know if there is a way somehow to launch a task or something via call api ?

Hoped some one can help me there .

**Comment by fredgnucc** [comment]
Hey guys , 

After reading documentation , 

Here is what i will do to automated the flow i will first create a volume on HMC side below the dedicated storage_group ( FCP mode )

After this i will create the volume on a9000r side .

So far from what understand based on documentation : 

 DPM runs a
background check of storage resources for FCP storage groups and, if necessary, changes the fulfillment
state. These checks are more frequent (every 10 minutes)

How can i force these check to be run from api side? is there a way?

**Comment by andy-maier** [comment]
Hi @fredgnucc. Sorry for the delay. I'll look into this.

**Comment by andy-maier** [comment]
In HMC/SE Version 2.14.1 (HMC API version 2.37), a new operation was introduced named "Start FCP Storage Discovery" that triggers the FC discovery and speeds up this process.

The zhmcclient package as of 0.26.0 does not yet support this operation. I'll see that it can be implemented soon.

**Comment by andy-maier** [comment]
@fredgnucc 
I have implemented the triggering of FCP discovery in a new `StorageGroup.dicsover()` method, along with a new `StorageGroup.get_connection_report()` method for retrieving the connection report resulting from the discovery. It is in PR #644 and targeted for the next minor release 0.27.0. Note that testcases are a larger topic, so for now it does not have a test.

Feel free to try it out, and if you do, let me know any issues.

**Comment by fredgnucc** [comment]
Hi Andy , 

Thanks for the work done , really appreciated , i will take a look next week when i come back from holiday .

Rgds Fred.

**Comment by andy-maier** [comment]
I merged the PR into master.

Note that I added an example that demonstrates it use: `examples/discover_storage_group.py`. I verified that this runs fine against a z14 with HMC API version 2.39 (2.37 is the minimum).

If you run into problems, please open a bug.

**Comment by andy-maier** [comment]
This function will be in the upcoming version 0.27.0. Closing this issue.
