### ISSUE TITLE
Exception raised while reading OS messages with stomp.py 6.1.x

### ISSUE THREAD

**Issue by kriolyth** [zhmcclient/python-zhmcclient#763]
**Describe the bug**
Trying to access OS Messages over STOMP protocol causes exceptions:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 346, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 193, in process_frame
    self.notify(frame_type, f)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 246, in notify
    notify_func(frame)
TypeError: on_message() missing 1 required positional argument: 'message'
```

**To Reproduce**
I've used a test program to get the messages:
```
import getpass
import zhmcclient

hmc_host = input("HMC host: ")
hmc_userid = input("HMC username: ")
hmc_password = getpass.getpass("HMC password: ")
cpc_name = input("CPC: ")
partition_name = input("LPAR: ")

session = zhmcclient.Session(hmc_host, hmc_userid, hmc_password)
client = zhmcclient.Client(session)
cpc = client.cpcs.find(name=cpc_name)
lpar = cpc.lpars.find(name=partition_name)

topic = lpar.open_os_message_channel(include_refresh_messages=True)

print("Subscribing for OS messages for lpar %s on CPC %s using "
      "notifications topic %s..." % (lpar.name, cpc.name, topic))

receiver = zhmcclient.NotificationReceiver(
    topic, hmc_host, hmc_userid, hmc_password)

try:
    while True:
        for headers, message in receiver.notifications():
            os_messages = [entry['message-text'].strip('\n')
                           for entry in message['os-messages']]

            print("Received %d messages" % len(os_messages))
            for os_msg in os_messages:
                print("OS message: %s" % os_msg)
except KeyboardInterrupt:
    print("Keyboard Interrupt - Leaving notification receiver loop...")
except Exception as exc:
    print("Exception: %s" % str(exc))
    raise
finally:
    print("Closing notification receiver...")
    receiver.close()
```

**Expected behavior**
I can retrieve the messages without errors.

**Environment information**
* Output of `python -m zhmcclient.debuginfo`:
Operating system: Linux 5.4.72-microsoft-standard-WSL2 on x86_64
Python implementation: CPython 3.6.9 (64 bit, wide unicode)
Python version: 3.6.9
zhmcclient version: 0.30.0
* HMC version: 2.15.0
* HMC API version: 3.8

As far as I could find, [NotificationListener](https://github.com/zhmcclient/python-zhmcclient/blob/b477e56fea7e9e5646bf7bb51be26a7d886e2e7a/zhmcclient/_notification.py#L252) became incompatible with stomp 6.1 after [this commit](https://github.com/jasonrbriggs/stomp.py/commit/24819247acede4e3429f0d7746b0d1133a96081f), where call signature for notifications has changed.

With stomp.py version 6.0.0 I retrieved the messages without issues.

**Comment by andy-maier** [comment]
Raised this issue with the stomp project as https://github.com/jasonrbriggs/stomp.py/issues/352.

I will circumvent the issue by pinning stomp.py for now. Expect a 0.31.0 release soon.

**Comment by andy-maier** [comment]
@kriolyth 
I have merged the fix for this into branch `stable_0.30`: https://github.com/zhmcclient/python-zhmcclient/tree/stable_0.30

Could you please try out whether it works for you?

**Comment by kriolyth** [comment]
Yes, it works, thank you! ❤️

**Comment by andy-maier** [comment]
zhmcclient 0.30.1 with the fix for this has been released today.
