### ISSUE TITLE
NVMe Addition Request

### ISSUE THREAD

**Issue by Noah-Markwica** [zhmcclient/python-zhmcclient#863]
Can you please add NVMe load and dump API functionality to zhmcclient and python-zhmcclient with support for the force option and secure-boot option for both load and dump

**Comment by andy-maier** [comment]
Hint: These operations are defined for classic mode on LPARs.

**Comment by andy-maier** [comment]
Moved to next release.

**Comment by penny56** [comment]
Hi Andy, any plan on DPM mode? Thanks.

**Comment by andy-maier** [comment]
Started working on it.

**Comment by andy-maier** [comment]
@penny56 The HMC as of z16 does not support NVMe Load/Dump in DPM mode, so the zhmcclient cannot support that either of course. I cannot say anything about possible plans to support that in DPM mode.

**Comment by andy-maier** [comment]
@Noah-Markwica, the support for NVME Load/Dump has been implemented in PR #1040 . You are welcome to try it out from that branch (check out the branch of the PR; install with `pip install .`). It is targeted for zhmcclient version 1.4.0.
