### ISSUE TITLE
SCSI Load passes `disk-partition-id` as string, not as integer.

### ISSUE THREAD

**Issue by Benjamin-Block** [zhmcclient/python-zhmcclient#934]
When trying to do a scsi-load with a non-default `disk-partition-id`/`bootprog` zhmc will pass the argument as string, and the API will complain:

    $ zhmc -n lpar scsi-load --force --disk-partition-id 2 T35 T35LP49 1900 500507630b01c320 4050406000000000
    Error: HTTPError: 400,7: the item being added, '2', is not the expected type..  Expected an integer.  at line: 1 column: 136 resource: /api/logical-partitions/81188060-7364-3579-8cfa-abfb9eb26845/operations/scsi-load [POST /api/logical-partitions/81188060-7364-3579-8cfa-abfb9eb26845/operations/scsi-load]

The Problem is here:

https://github.com/zhmcclient/python-zhmcclient/blob/92639a13a5d53283ae9862caf534d9be3b766ae8/zhmcclient/_lpar.py#L574

When applying this simple (experimental) patch:

    --- _lpar.old.py	2022-03-04 13:20:31.197940957 +0100
    +++ _lpar.py	2022-03-04 13:21:01.387940957 +0100
    @@ -571,7 +571,7 @@
             if load_parameter:
                 body['load-parameter'] = load_parameter
             if disk_partition_id is not None:
    -            body['disk-partition-id'] = disk_partition_id
    +            body['disk-partition-id'] = int(disk_partition_id)
             if operating_system_specific_load_parameters:
                 body['operating-system-specific-load-parameters'] = \
                     operating_system_specific_load_parameters

it works fine afterwards.

I'm using `zhmccli`/`zhmcclient` from PyPi:

    $ pip list --user
    Package             Version
    ------------------- ---------
    zhmccli             1.1.0
    zhmcclient          1.1.1

**Comment by andy-maier** [comment]
I will fix that in the zhmccli package. In the zhmcclient library, we are generally documenting the required types, but we are not verifying them, or converting incorrect types. If and when we increase the minimum Python version to 3.6, we can introduce type hints, but we are not there yet.

I have opened https://github.com/zhmcclient/zhmccli/issues/270 to fix this, and it is targeted for zhmccli 1.2.0, with rollback to 1.1.1.

**Comment by andy-maier** [comment]
zhmccli version 1.1.1 with the fix for this issue has been released.
